version: '3.8'

services:
  mysql:
    image: ajiayidebug/dsa3101:v1
    container_name: database
    environment:
      MYSQL_ROOT_PASSWORD: "MYSQL12345"
      MYSQL_ROOT_HOST: "root"
    ports:
      - "3306:3306"
    volumes:
      - ./data:/var/lib/mysql
      - ./all_databases.sql:/docker-entrypoint-initdb.d/all_databases.sql
    restart: unless-stopped
