version: '3.8'

services:
  mysql:
    image: ajiayidebug/dsa3101:v1
    container_name: database_docker
    environment:
      MYSQL_ROOT_PASSWORD: "MYSQL12345"
      MYSQL_ROOT_HOST: "root"
    ports:
      - "3307:3306"  # port will be 3307 in MySQL
    volumes:
      - ./data:/var/lib/mysql
      - ./all_databases.sql:/docker-entrypoint-initdb.d/all_databases.sql
    restart: unless-stopped

  app:
    build: .  
    container_name: DSA3101_19_app
    ports:
      - "3000:3000"  
    depends_on:
      - mysql 
    environment:
      - FLASK_ENV=deployment  # Environment variable for Flask
      - DATABASE_HOST=mysql
      - CONFIG_PATH=/DSA3101_group19/config.json
    restart: unless-stopped

